### PR TITLE
Update to WPE WebKit 2.22.5 and Poky Sumo

### PR DESCRIPTION
**Pull request by marhoy**
This pull request enables building the latest 2.22-release of WPE WebKit.
If you don't want to compile yourself, just **pull the finished image from `marhoy/balena-wpe:latest`**

Major changes:
- Update the build system to poky sumo
- Change layer from meta-wpe to meta-webkit from Igalia
- Update recipe to build the latest 2.22-release of WPE WebKit
- Enable all hardware decoding tricks for the raspberrypi3

Minor improvements:
- Add keyboard support
- Add ability to set rpi screen backlight brightness
- Add Tohora in the same way as balena-dash
- Add timezone-data to the image to you can specify the TZ-variable as usual
- Update to latest version of fbcp

### CODE REVIEW

**Comment by shaunmulligan** [comment]
I gave the pre-built image a test and it seems to work nicely. Great stuff @marhoy ! @imrehg and @petrosagg if you two are happy with the code, then lets get it merged.

**Comment by marhoy** [comment]
I also have an image compiled with all the latest stable versions: wpewebkit-2.24.1, libwpe-1.2 and cog-0.3, based on poky thud. (See `marhoy/balena-wpe:raspberrypi3-2.24.1-test` and `-test2` (`-test2` is built using openembedded-core instead of yocto poky)).

But for some reason, I have problems with an webpage that uses Google fonts. I wrote an issue about it in the [meta-webkit project](https://github.com/Igalia/meta-webkit/issues/101).

Any ideas about why it's like that?
What's wrong and how do I fix it?

**Comment by cpdbogo** [comment]
Sending keyboard strokes to the WPE messes up the image, at least for me..

Gives me following error:
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

**Comment by marhoy** [comment]
> Sending keyboard strokes to the WPE messes up the image, at least for me..
> 
> Gives me following error:
> xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

I connected a keyboard to my (normally keyboardless) rpi3, but 'm not able to reproduce.

1. Are you using the latest 22.2-image? (`2.22-latest` -> `raspberrypi3-2.22.5-75db63d`
2. Can you explain a bit more what you are doing to get these errors?

Note that X11 is not compiled/installed, so don't expect X-applications to work.

**Comment by marhoy** [comment]
> Sending keyboard strokes to the WPE messes up the image, at least for me..
> 
> Gives me following error:
> xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

Can you try the latest build (tag `raspberrypi3-2.22.5-b0c7448` (== `2.22-latest`)?
I have added `xkeyboard-config` to the image, which seems to solve the problem for me.

Martin

**Comment by cpdbogo** [comment]
> 
> 
> > Sending keyboard strokes to the WPE messes up the image, at least for me..
> > Gives me following error:
> > xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
> 
> Can you try the latest build (tag `raspberrypi3-2.22.5-b0c7448` (== `2.22-latest`)?
> I have added `xkeyboard-config` to the image, which seems to solve the problem for me.
> 
> Martin

Can confirm that it's working now. Thank you for this, it's awesome to see this being alive again.

**Comment by bitmorse** [comment]
cannot build using balena build in a multicontainer setup with this latest commit:
[Error]   Build failed
Error: (HTTP code 400) unexpected - No build stage in current context

reverting to a32216e2885528d900142a6ad164f84856de2469 and it builds fine.

**Comment by marhoy** [comment]
@bitmorse Maybe a stupid question, but: You have replaced line 2 of `balena-wpe/Dockerfile` with something meaningful, right?

**Comment by bitmorse** [comment]
thanks for the hint, indeed. I was relying on this project a git submodule and included in my own docker-compose.yml.

**Comment by petrosagg** [comment]
@marhoy @bitmorse I just updated the master branch with a prebuilt image

**Comment by chrisys** [comment]
@marhoy did you have any issues with YouTube on this new version? I'm looking at rolling all the updates into the balena-dash project but found when testing that YouTube videos don't play when using the update.

**Comment by marhoy** [comment]
@chrisys I don't think I tried :)

Can you test with`marhoy/balena-wpe:2.24-latest` (poky warrior and wpewebkit 2.24.2)?
I've changed my dashboard to that image and youtube seems to work there.
Can you give an example of a URL that does not work?

**Comment by chrisys** [comment]
@marhoy your image works great. It was any YouTube video I tried; for example I use the trick of putting a `-` between the `t` and the `u` in a YouTube URL to get a fullscreen looping video, e.g.: https://www.yout-ube.com/watch?v=4jXEuIHY9ic

Can you PR your latest changes?

**Comment by marhoy** [comment]
@chrisys OK, [pull request](https://github.com/balena-io-projects/balena-wpe/pull/46) made.

**Pull request merged**
